on:
  push:
    tags:
      - '*'

name: Release Builds
jobs:
  # linux:
  #   name: Linux
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: |
  #         git clone https://github.com/flutter/flutter.git
  #         cd flutter
  #         git checkout c8d051295a
  #     - run: echo ::add-path::`pwd`"/flutter/bin"
  #     - run: flutter precache
  #     - uses: actions/checkout@v2
  #       with:
  #         path: 'app'
  #     - name: Install required build tools for linux
  #       run: sudo apt-get update && sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev
  #     - run: |
  #         cd app
  #         flutter config --enable-linux-desktop
  #         flutter pub get
  #         flutter build linux --release
  #         cd build/linux/release
  #         zip -r linux-release.zip bundle
  #     - name: Create linux Release
  #       uses: ncipollo/release-action@v1
  #       with:
  #         artifacts: 'app/build/linux/release/linux-release.zip'
  #         token: ${{ secrets.TOKEN }}
  #         allowUpdates: true

  # android:
  #   name: Android
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: |
  #         git clone https://github.com/flutter/flutter.git
  #         cd flutter
  #         git checkout c8d051295a
  #     - run: echo ::add-path::`pwd`"/flutter/bin"
  #     - run: flutter precache
  #     - uses: actions/setup-java@v1
  #       with:
  #         java-version: '12.x'
  #     - uses: actions/checkout@v2
  #       with:
  #         path: 'app'
  #     - run: |
  #         cd app
  #         flutter pub get
  #         flutter build apk -t lib/main.dart --release
  #     - name: Create Android Release
  #       uses: ncipollo/release-action@v1
  #       with:
  #         artifacts: 'app/build/app/outputs/apk/release/app-release.apk'
  #         token: ${{ secrets.TOKEN }}
  #         allowUpdates: true

  # macos:
  #   name: MacOS
  #   runs-on: macos-latest
  #   steps:
  #     - run: |
  #         git clone https://github.com/flutter/flutter.git
  #         cd flutter
  #         git checkout c8d051295a
  #     - run: echo ::add-path::`pwd`"/flutter/bin"
  #     - run: flutter precache
  #     - uses: actions/checkout@v2
  #       with:
  #         path: 'app'
  #     - run: |
  #         cd app
  #         flutter config --enable-macos-desktop
  #         flutter pub get
  #         flutter build macos --release
  #         cd build/macos/Build/Products/Release
  #         ditto -c -k --sequesterRsrc --keepParent wowo.app macos-release.zip
  #     - uses: ncipollo/release-action@v1
  #       with:
  #         artifacts: 'app/build/macOS/Build/Products/Release/macos-release.zip'
  #         token: ${{ secrets.TOKEN }}
  #         allowUpdates: true

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - run: |
          git clone https://github.com/flutter/flutter.git
          cd flutter
          git checkout c8d051295a
      - run: echo ::add-path::"$(pwd)\flutter\bin"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: 'app'
      - run: |
          cd app
          flutter config --enable-windows-desktop
          flutter config ---no-enable-android
          flutter pub get
          flutter build windows --release
          cd build\windows\runner
          Compress-Archive -Path Release -DestinationPath windows-release.zip

      - name: Setup git configs
        run: |
          cd app
          git config --global user.name "hackerhgl"
          git config --global user.email "hackerhgl@gmail.com"

      - name: Sync branches
        run: |
          cd app
          git checkout gh-pages
          git stash
          git pull --rebase origin master

      - name: Run driver
        run: |
          cd app
          flutter drive -t test_driver/app.dart -d windows --dart-define="PLATFORM=windows" -v

      - name: Push screenshots
        run: |
          cd app
          git add .
          git commit -m "Screenshots by test driver [Windows]"
          git push origin gh-pages
      - name: Windows release build for github
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'app\build\windows\runner\windows-release.zip'
          token: ${{ secrets.TOKEN }}
          allowUpdates: true
